---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager.yaml
  - general.yaml
  - kube-state-metrics.yaml
  - kubernetes.yaml
  - node-exporter.yaml
  - prometheus.yaml
  - prometheus-operator.yaml
