---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
resources:
  - ../../upstream/grafana
  - service-monitor.yaml
patches:
  - deployment-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-configuration
    behavior: create
    files:
      - ./configuration/grafana.ini
  - name: grafana-dashboards-providers
    files:
      - ./dashboards/providers.yaml
  - name: grafana-dashboards-datasources
    files:
      - ./datasources/datasources.yaml
  - name: grafana-dashboards-prometheus-0
    files:
      - ./dashboards/prometheus/prometheus-stats.json
      - ./dashboards/prometheus/prometheus-remote-write.json
  - name: grafana-dashboards-kubernetes-0
    files:
      - ./dashboards/kubernetes/kubernetes-compute-resources-cluster.json
      - ./dashboards/kubernetes/kubernetes-compute-resources-namespace.json
      - ./dashboards/kubernetes/kubernetes-statefulsets.json
      - ./dashboards/kubernetes/kubernetes-persistent-volumes.json
  - name: grafana-dashboards-kubernetes-1
    files:
      - ./dashboards/kubernetes/kubernetes-compute-resources-namespace-workloads.json
      - ./dashboards/kubernetes/kubernetes-compute-resources-node-pods.json
      - ./dashboards/kubernetes/kubernetes-compute-resources-pod.json
  - name: grafana-dashboards-kubernetes-2
    files:
      - ./dashboards/kubernetes/kubernetes-api-server.json
      - ./dashboards/kubernetes/kubernetes-kubelet.json
  - name: grafana-dashboards-kubernetes-3
    files:
      - ./dashboards/kubernetes/kubernetes-network-cluster.json
      - ./dashboards/kubernetes/kubernetes-network-pods.json
      - ./dashboards/kubernetes/kubernetes-network-workload.json
  - name: grafana-dashboards-kubernetes-4
    files:
      - ./dashboards/kubernetes/kubernetes-network-namespace-pods.json
      - ./dashboards/kubernetes/kubernetes-network-namespace-workload.json
  - name: grafana-dashboards-infrastructure-0
    files:
      - ./dashboards/infrastructure/nodes.json
      - ./dashboards/infrastructure/infrastructure-nodes-details.json
      - ./dashboards/infrastructure/use-method-cluster.json
      - ./dashboards/infrastructure/use-method-node.json
  - name: grafana-dashboards-grafana-0
    files:
      - ./dashboards/grafana/grafana-internals.json
