---
# https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: visibility
  labels:
    alertmanager: visibility
  namespace: kube-visibility
spec:
  replicas: 1
  version: v0.20.0
  image: quay.io/prometheus/alertmanager
  serviceAccountName: alertmanager
  resources:
    requests:
      memory: 50Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  nodeSelector:
    kubernetes.io/os: linux
