---
# https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: visibility
  labels:
    prometheus: visibility
  namespace: kube-visibility
spec:
  replicas: 1
  version: v2.17.2
  image: quay.io/prometheus/prometheus
  serviceAccountName: prometheus
  enableAdminAPI: true
  resources:
    requests:
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  alerting:
    alertmanagers:
      - name: alertmanager-visibility
        namespace: kube-visibility
        port: web
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: visibility
  # This allow that any kind: ServiceMonitor that have the label 'kube-visibility.monitoring: "enabled"' will be scraped
  serviceMonitorSelector:
    matchLabels:
      kube-visibility.monitoring: "enabled"
  # This allow that any kind: PodMonitor that have the label 'kube-visibility.monitoring: "enabled"' will be scraped
  podMonitorSelector:
    matchLabels:
      kube-visibility.monitoring: "enabled"
  nodeSelector:
    kubernetes.io/os: linux
