---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator
  - ./prometheus-adapter
  - ./kube-state-metrics
  - ./node_exporter
  - ./prometheus
  - ./alertmanager
  - ./grafana
  - ./k8s-service-monitors
