apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
spec:
  replicas: 1 # {"$ref":"#/definitions/io.k8s.cli.setters.kube-state-metrics.replicas"}
  template:
    spec:
      containers:
        - name: kube-state-metrics
          resources:
            limits:
              cpu: 100m # {"$ref":"#/definitions/io.k8s.cli.setters.kube-state-metrics.resources-limits-cpu"}
              memory: 100Mi # {"$ref":"#/definitions/io.k8s.cli.setters.kube-state-metrics.resources-limits-memory"}
            requests:
              cpu: 50m # {"$ref":"#/definitions/io.k8s.cli.setters.kube-state-metrics.resources-requests-cpu"}
              memory: 50Mi # {"$ref":"#/definitions/io.k8s.cli.setters.kube-state-metrics.resources-requests-memory"}
