apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-exporter-clusterRole.yaml
  - node-exporter-clusterRoleBinding.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-service.yaml
  - node-exporter-serviceAccount.yaml
