---
# This element is used only whe you execute kustomize build upstream, just to test all the components
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
bases:
  - ./prometheus-operator
  - ./node_exporter
  - ./kube-state-metrics
  - ./prometheus-adapter
  - ./grafana
  - ./prometheus
  - ./alertmanager
