---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: production # change/remove/add more if you want
commonAnnotations:
  kube-visibility.manifest: "eks-full-ha-pv-k8s-1.14" # change/remove/add more if you want
bases:
  - ../../modifiers/k8s-1.14 # remember that this render all the base with neccesary changes in version
  # prometheus aditional folders resources
  - ./prometheus/pod-monitors
  - ./prometheus/service-monitors
  # kube-state-metrics aditional folders resources
resources:
  # prometheus resources
  - ./prometheus/prometheus-persistance.yaml
  - ./prometheus/prometheus-ingress.yaml
  - ./prometheus/alertmanager-persistance.yaml
  - ./prometheus/alertmanager-ingress.yaml
  # kube-state-metrics resources
patchesStrategicMerge:
  # prometheus patches
  - ./prometheus/alertmanager-alertmanager-patch.yaml
  - ./prometheus/prometheus-prometheus-patch.yaml
  # kube-state-metrics patches
  - ./kube-state-metrics/deployment-patch.yaml
