---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    name: grafana
  namespace: kube-visibility
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      serviceAccountName: grafana
      containers:
        - name: grafana
          image: grafana/grafana:6.7.3
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            # limits:
            #   cpu: 20m
            #   memory: 40Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: configuration
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              readOnly: true
            - name: storage
              mountPath: /var/lib/grafana
              readOnly: false
            - name: dashboards-providers
              mountPath: /etc/grafana/provisioning/dashboards/providers.yaml
              subPath: providers.yaml
              readOnly: true
            - name: dashboards-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboards-prometheus
              mountPath: /grafana/dashboards/prometheus
              readOnly: true
            - name: dashboards-kubernetes-0
              mountPath: /grafana/dashboards/kubernetes-0
              readOnly: true
            - name: dashboards-kubernetes-1
              mountPath: /grafana/dashboards/kubernetes-1
              readOnly: true
            - name: dashboards-network
              mountPath: /grafana/dashboards/network
              readOnly: true
            - name: dashboards-infrastructure
              mountPath: /grafana/dashboards/infrastructure
              readOnly: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: configuration
          configMap:
            name: configuration
        - name: storage
          emptyDir: {}
        - name: dashboards-providers
          configMap:
            name: dashboards-providers
        - name: dashboards-datasources
          configMap:
            name: dashboards-datasources
        - name: dashboards-prometheus
          configMap:
            name: dashboards-prometheus
        - name: dashboards-kubernetes-0
          configMap:
            name: dashboards-kubernetes-0
        - name: dashboards-kubernetes-1
          configMap:
            name: dashboards-kubernetes-1
        - name: dashboards-network
          configMap:
            name: dashboards-network
        - name: dashboards-infrastructure
          configMap:
            name: dashboards-infrastructure
      nodeSelector:
        beta.kubernetes.io/os: linux
