apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - alertmanager.yaml
  - kube-apiserver.yaml
  # - controller-manager.yaml
  - kube-dns.yaml
  # - grafana.yaml
  # - kube-scheduler.yaml
  - kube-state-metrics.yaml
  - kubelet.yaml
  - node-exporter.yaml
  - prometheus-operator.yaml
  - prometheus.yaml
